// ============================================================
// MegaCity Builder - Configuration & Building Definitions
// ============================================================

const CONFIG = {
    TILE_SIZE: 32,
    MAP_WIDTH: 60,
    MAP_HEIGHT: 60,

    INITIAL_MONEY: 50000,
    TAX_RATE_DEFAULT: 0.07,
    TAX_RATE_MIN: 0.01,
    TAX_RATE_MAX: 0.20,

    GAME_SPEEDS: [0, 1, 2, 4, 8],
    DEFAULT_SPEED: 1,
    TICK_INTERVAL: 800,

    DAY_LENGTH: 60,    // ticks per day
    MONTH_LENGTH: 30,  // days per month

    CAMERA: {
        MIN_ZOOM: 0.4,
        MAX_ZOOM: 3.0,
        ZOOM_SPEED: 0.15,
        PAN_SPEED: 12,
        EDGE_PAN_ZONE: 50,
        EDGE_PAN_SPEED: 6
    },

    COLORS: {
        GRASS: ['#4a7c3f', '#4e8244', '#528748', '#4a7c3f', '#3d6e34'],
        GRASS_DARK: ['#3d6e34', '#417239', '#45773d', '#3d6e34', '#36632e'],
        WATER: ['#2980b9', '#3498db', '#2e86c1', '#2471a3'],
        WATER_SHORE: '#c9a96e',
        SAND: '#f4d03f',
        DIRT: '#8B7355',
        ROAD: '#484848',
        ROAD_MARKING: '#cccccc',
        SIDEWALK: '#999999',
        GRID_LINE: 'rgba(0,0,0,0.06)',
        HIGHLIGHT_VALID: 'rgba(46, 204, 113, 0.35)',
        HIGHLIGHT_INVALID: 'rgba(231, 76, 60, 0.35)',
        SELECTION: 'rgba(52, 152, 219, 0.35)',
        DEMOLISH: 'rgba(231, 76, 60, 0.5)',
        TREE_TRUNK: '#5D4037',
        TREE_LEAVES: ['#2d8a4e', '#27ae60', '#229954', '#1e8449'],
        SKY_DAY: '#87CEEB',
        SKY_NIGHT: '#1a1a2e',
        SKY_SUNSET: '#e74c3c',
    },

    TERRAIN: {
        WATER_LEVEL: 0.28,
        SAND_LEVEL: 0.33,
        TREE_DENSITY: 0.12,
        ROCK_DENSITY: 0.02,
        NOISE_SCALE: 0.06,
        NOISE_OCTAVES: 4,
    },

    POPULATION: {
        GROWTH_RATE: 0.02,
        DECLINE_RATE: 0.01,
        MIN_HAPPINESS_FOR_GROWTH: 30,
    },

    SERVICES: {
        COVERAGE_DECAY: 0.15,
    }
};

// Building Type Definitions
const BUILDINGS = {
    // ---- ROADS ----
    road: {
        name: 'Road',
        category: 'infrastructure',
        cost: 50,
        size: [1, 1],
        maintenance: 1,
        color: '#484848',
        description: 'Connects buildings. Most structures require road access.',
        icon: '🛣️',
        needsRoad: false,
        needsPower: 0,
        needsWater: 0,
    },

    // ---- RESIDENTIAL ----
    house: {
        name: 'House',
        category: 'residential',
        cost: 500,
        size: [1, 1],
        maintenance: 5,
        capacity: 6,
        color: '#e8dcc8',
        roofColor: '#c0392b',
        wallColor: '#e8dcc8',
        height: 14,
        description: 'A cozy family home. Houses 6 residents.',
        icon: '🏠',
        needsRoad: true,
        needsPower: 1,
        needsWater: 1,
    },
    apartment: {
        name: 'Apartment',
        category: 'residential',
        cost: 3000,
        size: [2, 2],
        maintenance: 25,
        capacity: 30,
        color: '#d5ccc0',
        roofColor: '#7f8c8d',
        wallColor: '#d5ccc0',
        height: 28,
        description: 'Mid-rise apartments. Houses 30 residents.',
        icon: '🏢',
        needsRoad: true,
        needsPower: 4,
        needsWater: 4,
    },
    tower: {
        name: 'Residential Tower',
        category: 'residential',
        cost: 8000,
        size: [2, 2],
        maintenance: 60,
        capacity: 80,
        color: '#bdc3c7',
        roofColor: '#5dade2',
        wallColor: '#d6dbdf',
        height: 44,
        description: 'High-rise tower. Houses 80 residents.',
        icon: '🏙️',
        needsRoad: true,
        needsPower: 8,
        needsWater: 6,
    },

    // ---- COMMERCIAL ----
    shop: {
        name: 'Shop',
        category: 'commercial',
        cost: 800,
        size: [1, 1],
        maintenance: 8,
        income: 25,
        jobs: 5,
        color: '#f5b041',
        roofColor: '#d4ac0d',
        wallColor: '#fdebd0',
        height: 12,
        description: 'A small retail shop. 5 jobs, steady income.',
        icon: '🏪',
        needsRoad: true,
        needsPower: 1,
        needsWater: 1,
    },
    mall: {
        name: 'Shopping Mall',
        category: 'commercial',
        cost: 12000,
        size: [3, 3],
        maintenance: 100,
        income: 250,
        jobs: 50,
        happiness: 5,
        color: '#5dade2',
        roofColor: '#2e86c1',
        wallColor: '#d6eaf8',
        height: 22,
        description: 'Large shopping center. 50 jobs, happiness boost.',
        icon: '🏬',
        needsRoad: true,
        needsPower: 10,
        needsWater: 5,
    },
    office: {
        name: 'Office Tower',
        category: 'commercial',
        cost: 6000,
        size: [2, 2],
        maintenance: 45,
        income: 130,
        jobs: 35,
        color: '#85c1e9',
        roofColor: '#2980b9',
        wallColor: '#d4e6f1',
        height: 38,
        description: 'Modern offices. 35 jobs, good income.',
        icon: '🏢',
        needsRoad: true,
        needsPower: 5,
        needsWater: 3,
    },

    // ---- INDUSTRIAL ----
    factory: {
        name: 'Factory',
        category: 'industrial',
        cost: 4000,
        size: [2, 2],
        maintenance: 35,
        income: 90,
        jobs: 25,
        pollution: 20,
        color: '#aeb6bf',
        roofColor: '#7f8c8d',
        wallColor: '#d5d8dc',
        height: 18,
        description: 'Industrial factory. 25 jobs but creates pollution.',
        icon: '🏭',
        needsRoad: true,
        needsPower: 6,
        needsWater: 3,
    },
    warehouse: {
        name: 'Warehouse',
        category: 'industrial',
        cost: 2000,
        size: [2, 1],
        maintenance: 12,
        income: 35,
        jobs: 8,
        pollution: 3,
        color: '#d5d8dc',
        roofColor: '#aeb6bf',
        wallColor: '#eaecee',
        height: 12,
        description: 'Storage warehouse. 8 jobs, low pollution.',
        icon: '📦',
        needsRoad: true,
        needsPower: 2,
        needsWater: 1,
    },

    // ---- SERVICES ----
    police: {
        name: 'Police Station',
        category: 'services',
        cost: 5000,
        size: [2, 2],
        maintenance: 70,
        jobs: 15,
        serviceRadius: 10,
        serviceType: 'safety',
        color: '#2c3e50',
        roofColor: '#1a252f',
        wallColor: '#34495e',
        height: 16,
        description: 'Reduces crime in a 10-tile radius.',
        icon: '🚔',
        needsRoad: true,
        needsPower: 3,
        needsWater: 2,
    },
    fire_station: {
        name: 'Fire Station',
        category: 'services',
        cost: 5000,
        size: [2, 2],
        maintenance: 70,
        jobs: 15,
        serviceRadius: 10,
        serviceType: 'fire',
        color: '#e74c3c',
        roofColor: '#c0392b',
        wallColor: '#f1948a',
        height: 16,
        description: 'Fire protection in a 10-tile radius.',
        icon: '🚒',
        needsRoad: true,
        needsPower: 3,
        needsWater: 2,
    },
    hospital: {
        name: 'Hospital',
        category: 'services',
        cost: 10000,
        size: [3, 2],
        maintenance: 120,
        jobs: 35,
        serviceRadius: 12,
        serviceType: 'health',
        color: '#fdfefe',
        roofColor: '#d5d8dc',
        wallColor: '#f2f3f4',
        height: 22,
        description: 'Healthcare for citizens. 12-tile radius.',
        icon: '🏥',
        needsRoad: true,
        needsPower: 6,
        needsWater: 4,
    },
    school: {
        name: 'School',
        category: 'services',
        cost: 4000,
        size: [2, 2],
        maintenance: 50,
        jobs: 12,
        serviceRadius: 8,
        serviceType: 'education',
        color: '#f0b27a',
        roofColor: '#e67e22',
        wallColor: '#fdebd0',
        height: 14,
        description: 'Educates citizens. Boosts growth potential.',
        icon: '🏫',
        needsRoad: true,
        needsPower: 3,
        needsWater: 2,
    },

    // ---- UTILITIES ----
    power_plant: {
        name: 'Coal Power',
        category: 'utilities',
        cost: 8000,
        size: [3, 3],
        maintenance: 90,
        jobs: 15,
        powerOutput: 60,
        pollution: 30,
        color: '#616a6b',
        roofColor: '#4d5656',
        wallColor: '#808b8d',
        height: 24,
        description: 'Generates 60 power. High pollution.',
        icon: '🏭',
        needsRoad: true,
        needsPower: 0,
        needsWater: 5,
    },
    solar_farm: {
        name: 'Solar Farm',
        category: 'utilities',
        cost: 12000,
        size: [3, 3],
        maintenance: 25,
        jobs: 4,
        powerOutput: 35,
        pollution: 0,
        color: '#1a5276',
        roofColor: '#154360',
        wallColor: '#1a5276',
        height: 4,
        description: 'Clean solar energy. Generates 35 power.',
        icon: '☀️',
        needsRoad: true,
        needsPower: 0,
        needsWater: 1,
    },
    wind_turbine: {
        name: 'Wind Turbine',
        category: 'utilities',
        cost: 5000,
        size: [1, 1],
        maintenance: 12,
        jobs: 2,
        powerOutput: 12,
        pollution: 0,
        color: '#ecf0f1',
        roofColor: '#d5d8dc',
        wallColor: '#ecf0f1',
        height: 36,
        description: 'Clean wind energy. 12 power each.',
        icon: '💨',
        needsRoad: true,
        needsPower: 0,
        needsWater: 0,
    },
    water_tower: {
        name: 'Water Tower',
        category: 'utilities',
        cost: 3000,
        size: [1, 1],
        maintenance: 15,
        jobs: 2,
        waterOutput: 30,
        color: '#3498db',
        roofColor: '#2980b9',
        wallColor: '#85c1e9',
        height: 28,
        description: 'Supplies 30 units of water.',
        icon: '💧',
        needsRoad: true,
        needsPower: 2,
        needsWater: 0,
    },
    water_pump: {
        name: 'Water Plant',
        category: 'utilities',
        cost: 7000,
        size: [2, 2],
        maintenance: 40,
        jobs: 8,
        waterOutput: 60,
        color: '#2471a3',
        roofColor: '#1a5276',
        wallColor: '#5dade2',
        height: 14,
        description: 'Large water treatment. Supplies 60 water.',
        icon: '🚰',
        needsRoad: true,
        needsPower: 4,
        needsWater: 0,
    },

    // ---- RECREATION ----
    park: {
        name: 'Park',
        category: 'recreation',
        cost: 400,
        size: [2, 2],
        maintenance: 8,
        happiness: 10,
        serviceRadius: 5,
        serviceType: 'happiness',
        color: '#27ae60',
        height: 2,
        description: 'Green space. Boosts nearby happiness.',
        icon: '🌳',
        needsRoad: false,
        needsPower: 0,
        needsWater: 1,
    },
    stadium: {
        name: 'Stadium',
        category: 'recreation',
        cost: 20000,
        size: [4, 4],
        maintenance: 180,
        jobs: 60,
        happiness: 25,
        income: 120,
        serviceRadius: 15,
        serviceType: 'happiness',
        color: '#8e44ad',
        roofColor: '#6c3483',
        wallColor: '#bb8fce',
        height: 20,
        description: 'Massive entertainment venue. Huge happiness.',
        icon: '🏟️',
        needsRoad: true,
        needsPower: 12,
        needsWater: 8,
    },
    fountain: {
        name: 'Fountain',
        category: 'recreation',
        cost: 250,
        size: [1, 1],
        maintenance: 3,
        happiness: 3,
        color: '#85c1e9',
        height: 6,
        description: 'Decorative water fountain.',
        icon: '⛲',
        needsRoad: false,
        needsPower: 0,
        needsWater: 1,
    },
    monument: {
        name: 'Monument',
        category: 'recreation',
        cost: 5000,
        size: [1, 1],
        maintenance: 5,
        happiness: 8,
        color: '#d5d8dc',
        roofColor: '#aeb6bf',
        wallColor: '#f2f3f4',
        height: 30,
        description: 'Inspiring city monument.',
        icon: '🗽',
        needsRoad: false,
        needsPower: 1,
        needsWater: 0,
    },
};

const CATEGORIES = {
    infrastructure: { name: 'Roads', icon: '🛣️', color: '#7f8c8d' },
    residential:    { name: 'Residential', icon: '🏠', color: '#27ae60' },
    commercial:     { name: 'Commercial', icon: '🏪', color: '#3498db' },
    industrial:     { name: 'Industrial', icon: '🏭', color: '#95a5a6' },
    services:       { name: 'Services', icon: '🚔', color: '#e74c3c' },
    utilities:      { name: 'Utilities', icon: '⚡', color: '#f39c12' },
    recreation:     { name: 'Recreation', icon: '🌳', color: '#2ecc71' },
};

// Disaster types
const DISASTERS = {
    fire: {
        name: 'Fire',
        icon: '🔥',
        chance: 0.002,
        message: 'A fire has broken out!',
    },
    earthquake: {
        name: 'Earthquake',
        icon: '🌋',
        chance: 0.0005,
        message: 'An earthquake shakes the city!',
    },
};
